nginx::nginx_vhosts:
  "keystone.%{hiera('stack::domain')}":
     listen_port: 5000
     proxy: "http://keystone.%{hiera('stack::domain')}:5000"
  "glance.%{hiera('stack::domain')}":
     listen_port: 9292
     proxy: "http://glance.%{hiera('stack::domain')}:9292"
  "nova.%{hiera('stack::domain')}":
     listen_port: 8774
     proxy: "http://nova.%{hiera('stack::domain')}:8774"
  "neutron.%{hiera('stack::domain')}":
     listen_port: 9696
     proxy: "http://neutron.%{hiera('stack::domain')}:9696"
  "cinder.%{hiera('stack::domain')}":
     listen_port: 8776
     proxy: "http://cinder.%{hiera('stack::domain')}:8776"
  "stack.%{hiera('stack::domain')}":
     listen_port: 80
     proxy: "http://horizon.%{hiera('stack::domain')}"

classes:
  - nginx
